### ISSUE TITLE
Superantipoison secondary

### ISSUE THREAD

**Issue by bverpaalen** [climbridecode/herblore-recipes#13]
When hoovering over superantipoison ingredients unicorn horn is shown as the secondary ingredient which should be unicorn horn dust.

**Comment by bverpaalen** [comment]
I tried to fix this with the following PR: https://github.com/climbridecode/herblore-recipes/pull/12
It hasn't been tested yet though.

**Comment by climbridecode** [comment]
It'll show over unicorn horns and unicorn horn dust too. Took a look at your PR and approved it as it makes more sense :) thanks for catching that!

**Comment by climbridecode** [comment]
https://github.com/runelite/plugin-hub/pull/4457

**Comment by climbridecode** [comment]
https://github.com/runelite/plugin-hub/pull/4457
