### ISSUE TITLE
Added tooltip visibility toggle for Imp repellent

### ISSUE THREAD

**Issue by Rowan-Mulder** [climbridecode/herblore-recipes#15]
I like how this plugin helps to remind me of common secondaries, but Imp repellent may be a tad out of place.
Could a visibility toggle be added to hide the tooltips for Imp repellent?
Personally, I can't see what potion the secondaries are used for on the resolution I usually play either way.
(screenshot example on a wide resolution window)
![image](https://github.com/climbridecode/herblore-recipes/assets/62886548/8d86636d-dbd3-44c4-9743-3cc43e15c252)

**Comment by climbridecode** [comment]
That's so funny hahah, I knew this potion would cause problems. I'll probably shorten this list to just "flowers" or something, have it be a special case.

**Comment by climbridecode** [comment]
@Rowan-Mulder Here's a sneak peek:
Config option turned off:
![ImpRepellentToggleOff](https://github.com/climbridecode/herblore-recipes/assets/105681785/ebbaab2d-cbe7-4bd7-b2e6-a35346ef15d9)

Config potion turned on:
![ImpRepellentToggleOn](https://github.com/climbridecode/herblore-recipes/assets/105681785/c2c51330-f05e-474f-a0f9-9d89ad60bd2d)

**Comment by climbridecode** [comment]
Will be available when this PR is merged: https://github.com/runelite/plugin-hub/pull/4676

**Comment by Rowan-Mulder** [comment]
That's looking very nice, thanks!
