### ISSUE TITLE
Tooltip on flowers all on one line

### ISSUE THREAD

**Issue by robmonte** [climbridecode/herblore-recipes#17]
Somehow the tooltip text on all of the flower items (from mithril seeds) got collapsed into a single line. This causes the tooltip text to be nearly as wide as my entire monitor.

**Comment by robmonte** [comment]
![image](https://github.com/climbridecode/herblore-recipes/assets/17119716/57af64c0-35fb-48fd-b72e-29e2914f02e9)

**Comment by climbridecode** [comment]
Can you toggle the config option for Imp Repellent?
![ImpRepellentOption](https://github.com/climbridecode/herblore-recipes/assets/105681785/cc573507-9705-4366-9c04-a3888e2a5a34)

**Comment by robmonte** [comment]
Yeah that hides it, but I think the real issue is that it should be formatted different. (I was mistakenly thinking this plugin previously had line breaks in the tooltip, but I was mixing it up with the Green Thumb plugin for farming).

I'm also now noticing the text doesn't properly explain Imp repellent either. For some reason in my screenshot it shows "Dwarf remains" as the 1st ingredient?

However at this moment it doesn't even list a 1st ingredient at all.

I think the tooltip text should look like: 
```
level 3: Imp repellent (1st: Anchovy oil -
  2nd: Flowers:
  - Marigold
  - Rosemary
  - Nasturtium
  - Red, Blue, Yellow, Purple, Orange, Mixed, Assorted, Black, or White flowers)
```

**Comment by climbridecode** [comment]
Good suggestion! I thought I patched the dwarf remains bug out - which version of the plugin are you using? There are also line breaks in the tooltips, but not on the potion's ingredients lists (though that can change for long lists like this)

**Comment by robmonte** [comment]
Yeah it was fixed as of my last comment when I re-opened the client. I guess I had taken the screenshot just before the Runelite plugin update was merged that fixed the dwarf remains.
