### ISSUE TITLE
Herb Tooltip not showing.

### ISSUE THREAD

**Issue by JakeWakeman** [climbridecode/herblore-recipes#21]
Hi,

The tooltip does not seem to work on herbs. Grimy or not. The setting is set to show tooltip as can be seen in screenshots. Seems to be working fine for seeds.

Edit: the seeds works from another plugin, so i guess it might just be not working at all
![image](https://github.com/climbridecode/herblore-recipes/assets/95646263/b2e67827-3a30-4493-9efe-3271fac27727)
![image](https://github.com/climbridecode/herblore-recipes/assets/95646263/93af405a-56e2-4545-97db-1fb6e883e467)
![image](https://github.com/climbridecode/herblore-recipes/assets/95646263/86a13bcc-19e8-4304-a51e-82de77a91c0a)
![image](https://github.com/climbridecode/herblore-recipes/assets/95646263/492d9e54-adab-4679-a844-7433097efefe)

**Comment by rwgnr** [comment]
Seeing the same thing, no tooltips being displayed

**Comment by zeroquinc** [comment]
Same here

**Comment by JakeWakeman** [comment]
Still broken :/

![image](https://github.com/user-attachments/assets/be16f82c-3771-4e52-b562-592c6302fc83)

**Comment by climbridecode** [comment]
@JakeWakeman Does this happen on every run or only intermittently? Haven't been able to reproduce yet.

**Comment by JakeWakeman** [comment]
Hey dude, it seems to have worked after a reinstall and restart. The issue could be that the client needs to be restarted after install?

**Comment by climbridecode** [comment]
@JakeWakeman I did put out an update recently that should resolve the issue 🤞 , will close this but please feel free to open a new one if you see the crash again :).
