### ISSUE TITLE
Tooltip in Seed Vault requires 'Show Tooltip in Inventory' to be active in order to work. 

### ISSUE THREAD

**Issue by LukeD1357** [climbridecode/herblore-recipes#27]
Currently using version 1.7.3 of the plugin. 

The tooltip for in the Seed Vault will only show if I also have the 'Show Tooltip in Inventory' activated.
It does not work with this option disabled.

With Inventory option OFF (no tooltip):
![image](https://github.com/user-attachments/assets/16d12ce3-184f-426d-93ce-af694afe1c90)

With Inventory option ON (tooltip showing):
![image](https://github.com/user-attachments/assets/5bebd8a0-7727-4047-a680-b864f3330d84)

**Comment by climbridecode** [comment]
Hey thanks for reporting this! Thankfully should be a quick fix. Next release will fix it :)
