### ISSUE TITLE
Causing FPS to tank

### ISSUE THREAD

**Issue by killerjerick** [climbridecode/herblore-recipes#3]
Hi, just letting you know that on the latest version of Runelite 1.9.8, this plugin is causing the FPS to tank upon mousing over any object in game, including in inventory.

**Comment by climbridecode** [comment]
Sweet, thanks for letting me know! Haven't been playing and haven't updated this plugin in quite a while.

Think a refactor is in order :)

**Comment by climbridecode** [comment]
What are your PC specs?
I haven't been able to reproduce this and haven't gotten other FPS complaints. Does it drop your FPS to single digits? And does it happen even if you re-hover over the same item?

**Comment by climbridecode** [comment]
Closing the issue. Refactored the plugin to pre-load the cache - tooltips are directly available and retrieved when hovering over a herblore item.
