### ISSUE TITLE
Printing to terminal all the time

### ISSUE THREAD

**Issue by TicTac7x** [climbridecode/herblore-recipes#4]
Plugin seems to be printing stuff all the time, the output is something like this:
![image](https://user-images.githubusercontent.com/75637554/222897236-69f338b9-353f-46c8-82d3-10b46e6feab9.png)

**Comment by Speshkitty** [comment]
This seems to have been technically fixed by PR #1, but never actually merged with Runelite

**Comment by climbridecode** [comment]
Sorry about that! Will be fixed w/ this merge: https://github.com/runelite/plugin-hub/pull/4324
