### ISSUE TITLE
Add tooltip to Seed Vault @ Farming Guild

### ISSUE THREAD

**Issue by trepidatio** [climbridecode/herblore-recipes#5]
Would be nice to have (the option to show) these tooltips over herb seeds (etc.) in the Seed Vault.

The plugin [Green Thumb](https://github.com/Asthereon/green-thumb) can handle this, but I feel that your plugin presents the information better. And having all its features enabled at the same time leads to redundant/duplicant info in one's bank.

(Thank you for the plugin, it's super helpful as an iron.)

**Comment by climbridecode** [comment]
Good suggestion :) will be included w/ this PR merge: https://github.com/runelite/plugin-hub/pull/4324
