### ISSUE TITLE
Split "Primaries" into grimy and cleaned herbs

### ISSUE THREAD

**Issue by TicTac7x** [climbridecode/herblore-recipes#8]
Make it possible to show tooltips for example when hovering cleaned herbs and not when hovering grimy herbs.

This would be really helpful, since the tooltip is too much when cleaning 1000s of herbs, which makes me disable the plugin temporarily.

**Comment by climbridecode** [comment]
Sounds good! Adding this config option.

Plugin will include this when this PR is merged: https://github.com/runelite/plugin-hub/pull/4388

**Comment by TicTac7x** [comment]
There's something else that i noticed, doing vorkath and using potions that
are considered "second ingredients". Maybe it would be also possible to
ignore finished potions for the tooltips?

**Comment by climbridecode** [comment]
> There's something else that i noticed, doing vorkath and using potions that
are considered "second ingredients". Maybe it would be also possible to
ignore finished potions for the tooltips?

This is coming soon! :) There will be a configuration option to toggle tooltips on Potions, and, separately, on "Complex Bases" which are potions that serve as bases for other potions.

For example, when hovering over an Antidote++ with both of these config options enabled, you'll see "Requirements for Antidote++" as well as "Base for: Anti-venom...". If you disable both of these options, there will be no tooltip. If you only enable one of the two options, you'll see "Requirements for..." OR "Base for..." depending on which option is enabled!

Another handy tip if the tooltips are too cumbersome is setting the Keybind option, so tooltips will only appear when pressing down the key and hovering over an item.

**Comment by climbridecode** [comment]
Look out for version 1.7! When this gets merged: https://github.com/runelite/plugin-hub/pull/4398
